this_tuple = (1,2,4,5,2,2)
print(this_tuple.index(2))
print(sum(this_tuple))
print(all(this_tuple))
print(any(this_tuple))
print(sorted(this_tuple))
a = enumerate(this_tuple) 
print(dict(a))
print(this_tuple.count(2)) 